### ISSUE TITLE
4.0.9a GhostPart error - no top.same method when crafting covers

### ISSUE THREAD

**Issue by bmwalter68** [bdew/covers#7]
java.lang.NoSuchMethodError: net.bdew.lib.crafting.RecipeMatcher$Entry.same()Lnet/bdew/lib/crafting/RecipeMatcher$Rule;
    at net.bdew.covers.recipes.RecipeGhostPart$$anonfun$verifyAndCreateResult$1$$anonfun$apply$1$$anonfun$apply$3.apply(RecipeGhostPart.scala:32)
    at net.bdew.covers.recipes.RecipeGhostPart$$anonfun$verifyAndCreateResult$1$$anonfun$apply$1$$anonfun$apply$3.apply(RecipeGhostPart.scala:35)
    at scala.Option$WithFilter$$anonfun$withFilter$1.apply(Option.scala:209)
    at scala.Option$WithFilter$$anonfun$withFilter$1.apply(Option.scala:209)
    at scala.Option$WithFilter.map(Option.scala:206)
    at net.bdew.covers.recipes.RecipeGhostPart$$anonfun$verifyAndCreateResult$1$$anonfun$apply$1.apply(RecipeGhostPart.scala:31)
    at net.bdew.covers.recipes.RecipeGhostPart$$anonfun$verifyAndCreateResult$1$$anonfun$apply$1.apply(RecipeGhostPart.scala:30)
    at scala.Option.flatMap(Option.scala:170)
    at net.bdew.covers.recipes.RecipeGhostPart$$anonfun$verifyAndCreateResult$1.apply(RecipeGhostPart.scala:30)
    at net.bdew.covers.recipes.RecipeGhostPart$$anonfun$verifyAndCreateResult$1.apply(RecipeGhostPart.scala:29)
    at scala.Option.flatMap(Option.scala:170)
    at net.bdew.covers.recipes.RecipeGhostPart$.verifyAndCreateResult(RecipeGhostPart.scala:29)
    at net.bdew.covers.recipes.MicroblockRecipe.func_77569_a(MicroblockRecipe.scala:35)
    at net.minecraft.item.crafting.CraftingManager.func_82787_a(SourceFile:1234)
    at net.minecraft.inventory.ContainerWorkbench.func_75130_a(SourceFile:54)
    at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:88)
    at net.minecraft.inventory.Slot.func_75215_d(Slot.java:72)
    at net.minecraft.inventory.Container.func_184996_a(Container.java:191)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
    at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:579)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:558)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by bdew** [comment]
Your versions of BDLib and Simple covers are mismached. You cut the relevant part of the report so i can't see which exactly those are, but updating to the latest for both should fix that.
